apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-go
  namespace: infra
spec:
  interval: 1m
  chart:
    spec:
      chart: ./service-go
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    env:
      MONGO_URI: "mongodb://mongo.infra.svc.cluster.local:27017"
      RABBIT_URL: "amqp://guest:guest@rabbitmq.infra.svc.cluster.local:5672/"
      REDIS_ADDR: "redis.infra.svc.cluster.local:6379"
      KAFKA_BROKER: "kafka.infra.svc.cluster.local:9092"
